import type { Company, Product, Deal, Proposal, OutreachMessage, Activity, DashboardMetrics } from './b2b-types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Apex Logistics',
    industry: 'Supply Chain',
    size: 'enterprise',
    website: 'apexlogistics.com',
    logo: 'AL',
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.chen@apexlogistics.com',
    contactTitle: 'VP of Operations',
    country: 'USA',
    annualRevenue: 250000000,
    tags: ['hot', 'expansion'],
    createdAt: '2024-01-15',
  },
  {
    id: 'c2',
    name: 'NovaTech Industries',
    industry: 'Manufacturing',
    size: 'enterprise',
    website: 'novatech.io',
    logo: 'NT',
    contactName: 'Marcus Rivera',
    contactEmail: 'm.rivera@novatech.io',
    contactTitle: 'CTO',
    country: 'Germany',
    annualRevenue: 480000000,
    tags: ['strategic'],
    createdAt: '2024-02-03',
  },
  {
    id: 'c3',
    name: 'Meridian Finance',
    industry: 'Financial Services',
    size: 'sme',
    website: 'meridianfin.com',
    logo: 'MF',
    contactName: 'Priya Patel',
    contactEmail: 'priya@meridianfin.com',
    contactTitle: 'Head of IT',
    country: 'UK',
    annualRevenue: 45000000,
    tags: ['renewal'],
    createdAt: '2024-03-10',
  },
  {
    id: 'c4',
    name: 'Skyward Retail',
    industry: 'Retail',
    size: 'sme',
    website: 'skywardretail.com',
    logo: 'SR',
    contactName: 'Jake Thompson',
    contactEmail: 'jake.t@skywardretail.com',
    contactTitle: 'CEO',
    country: 'Canada',
    annualRevenue: 18000000,
    tags: ['new'],
    createdAt: '2024-04-22',
  },
  {
    id: 'c5',
    name: 'Quantum Healthcare',
    industry: 'Healthcare',
    size: 'enterprise',
    website: 'quantumhc.com',
    logo: 'QH',
    contactName: 'Dr. Aisha Williams',
    contactEmail: 'a.williams@quantumhc.com',
    contactTitle: 'Chief Digital Officer',
    country: 'USA',
    annualRevenue: 920000000,
    tags: ['hot', 'strategic'],
    createdAt: '2024-01-28',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Enterprise Suite',
    description: 'Full-stack B2B workflow automation with unlimited users, AI assistants, and custom integrations.',
    price: 48000,
    currency: 'USD',
    pricingModel: 'fixed',
    category: 'Platform',
    features: ['Unlimited users', 'AI deal scoring', 'Custom approval chains', 'API access', 'Dedicated support'],
    isActive: true,
  },
  {
    id: 'p2',
    name: 'Professional Plan',
    description: 'Per-seat SaaS plan for growing teams. Includes deal pipeline, proposals, and basic approvals.',
    price: 149,
    currency: 'USD',
    pricingModel: 'per_seat',
    category: 'Platform',
    features: ['Up to 50 users', 'Deal pipeline', 'Proposal builder', '2-level approvals', 'Email integration'],
    minSeats: 5,
    isActive: true,
  },
  {
    id: 'p3',
    name: 'AI Outreach Add-on',
    description: 'Claude-powered personalized outreach generation. Unlimited campaigns.',
    price: 800,
    currency: 'USD',
    pricingModel: 'fixed',
    category: 'AI Add-on',
    features: ['Unlimited campaigns', 'Tone customization', 'Company research synthesis', 'A/B subject lines'],
    isActive: true,
  },
  {
    id: 'p4',
    name: 'Advanced Approval Engine',
    description: 'Multi-level approval workflows with SLA tracking, escalation, and audit trails.',
    price: 1200,
    currency: 'USD',
    pricingModel: 'fixed',
    category: 'Module',
    features: ['Unlimited approval chains', 'SLA timers', 'Escalation rules', 'Audit log', 'e-Signature ready'],
    isActive: true,
  },
  {
    id: 'p5',
    name: 'Analytics & Intelligence',
    description: 'Deep deal analytics, win/loss analysis, and revenue forecasting powered by AI.',
    price: 600,
    currency: 'USD',
    pricingModel: 'fixed',
    category: 'AI Add-on',
    features: ['Revenue forecast', 'Win/loss analysis', 'Cycle time tracking', 'Custom dashboards'],
    isActive: true,
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd1',
    title: 'Apex Logistics — Enterprise Suite + AI',
    companyId: 'c1',
    value: 248000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 75,
    ownerId: 'u1',
    ownerName: 'Alex Morgan',
    productIds: ['p1', 'p3', 'p5'],
    notes: 'Sarah confirmed budget approved. Legal review in progress.',
    nextAction: 'Send revised contract',
    nextActionDate: '2024-05-02',
    createdAt: '2024-02-10',
    updatedAt: '2024-04-28',
    closedAt: null,
    aiScore: 82,
    aiInsight: 'High win probability. Decision maker engaged. Main risk: procurement delay.',
  },
  {
    id: 'd2',
    title: 'NovaTech — Full Platform Rollout',
    companyId: 'c2',
    value: 384000,
    currency: 'USD',
    stage: 'proposal',
    probability: 55,
    ownerId: 'u1',
    ownerName: 'Alex Morgan',
    productIds: ['p1', 'p4'],
    notes: 'Marcus wants to include 3 subsidiaries. Proposal needs adjustment.',
    nextAction: 'Revise proposal for multi-entity',
    nextActionDate: '2024-05-03',
    createdAt: '2024-03-01',
    updatedAt: '2024-04-25',
    closedAt: null,
    aiScore: 61,
    aiInsight: 'Complex deal with multi-stakeholder involvement. Recommend executive sponsor alignment.',
  },
  {
    id: 'd3',
    title: 'Meridian Finance — Pro Plan Renewal',
    companyId: 'c3',
    value: 35700,
    currency: 'USD',
    stage: 'qualified',
    probability: 90,
    ownerId: 'u2',
    ownerName: 'Jenna Park',
    productIds: ['p2', 'p4'],
    notes: 'Renewal + upgrade to Advanced Approval Engine.',
    nextAction: 'Send proposal',
    nextActionDate: '2024-05-01',
    createdAt: '2024-04-15',
    updatedAt: '2024-04-29',
    closedAt: null,
    aiScore: 91,
    aiInsight: 'Existing customer renewal with expansion. Very high confidence. Expedite proposal.',
  },
  {
    id: 'd4',
    title: 'Quantum Healthcare — Strategic Partnership',
    companyId: 'c5',
    value: 720000,
    currency: 'USD',
    stage: 'prospecting',
    probability: 25,
    ownerId: 'u1',
    ownerName: 'Alex Morgan',
    productIds: ['p1', 'p3', 'p4', 'p5'],
    notes: 'Initial discovery call went well. Need to map stakeholders.',
    nextAction: 'Schedule technical demo',
    nextActionDate: '2024-05-05',
    createdAt: '2024-04-20',
    updatedAt: '2024-04-28',
    closedAt: null,
    aiScore: 38,
    aiInsight: 'Early stage but enormous potential. Healthcare compliance requirements need attention.',
  },
  {
    id: 'd5',
    title: 'Skyward Retail — Starter Package',
    companyId: 'c4',
    value: 17880,
    currency: 'USD',
    stage: 'closed_won',
    probability: 100,
    ownerId: 'u2',
    ownerName: 'Jenna Park',
    productIds: ['p2'],
    notes: 'Closed! Onboarding scheduled for May 6.',
    nextAction: 'Kickoff onboarding',
    nextActionDate: '2024-05-06',
    createdAt: '2024-03-20',
    updatedAt: '2024-04-26',
    closedAt: '2024-04-26',
    aiScore: 100,
    aiInsight: 'Deal closed successfully. Focus on onboarding and expansion opportunities.',
  },
];

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: 'pr1',
    dealId: 'd1',
    companyId: 'c1',
    title: 'Enterprise Automation Suite — Apex Logistics',
    status: 'viewed',
    executiveSummary: 'A tailored enterprise solution to unify Apex Logistics\'s procurement, vendor management, and approval workflows — reducing deal cycle time by an estimated 40% and eliminating manual coordination overhead.',
    content: '',
    validUntil: '2024-05-15',
    totalValue: 248000,
    currency: 'USD',
    lineItems: [
      { id: 'li1', productId: 'p1', productName: 'Enterprise Suite', description: 'Annual license', quantity: 1, unitPrice: 48000, discount: 10, total: 43200 },
      { id: 'li2', productId: 'p3', productName: 'AI Outreach Add-on', description: 'Annual', quantity: 1, unitPrice: 800, discount: 0, total: 800 },
      { id: 'li3', productId: 'p5', productName: 'Analytics & Intelligence', description: 'Annual', quantity: 1, unitPrice: 600, discount: 0, total: 600 },
    ],
    approvalSteps: [
      { id: 'as1', approverName: 'Director of Sales', approverEmail: 'sales-dir@company.com', approverRole: 'Sales Director', status: 'approved', comment: 'Pricing looks good.', decidedAt: '2024-04-20', order: 1 },
      { id: 'as2', approverName: 'VP Revenue', approverEmail: 'vp-rev@company.com', approverRole: 'VP Revenue', status: 'approved', comment: 'Approved with discount noted.', decidedAt: '2024-04-22', order: 2 },
      { id: 'as3', approverName: 'CFO', approverEmail: 'cfo@company.com', approverRole: 'CFO', status: 'pending', comment: '', decidedAt: null, order: 3 },
    ],
    currentApprovalStep: 2,
    createdAt: '2024-04-18',
    sentAt: '2024-04-23',
    viewedAt: '2024-04-24',
  },
  {
    id: 'pr2',
    dealId: 'd2',
    companyId: 'c2',
    title: 'Full Platform — NovaTech Industries',
    status: 'draft',
    executiveSummary: 'Comprehensive digital transformation of NovaTech\'s B2B procurement and approval processes across all three subsidiary entities, with unified reporting and AI-driven insights.',
    content: '',
    validUntil: '2024-05-20',
    totalValue: 384000,
    currency: 'USD',
    lineItems: [
      { id: 'li4', productId: 'p1', productName: 'Enterprise Suite', description: 'Annual × 3 entities', quantity: 3, unitPrice: 48000, discount: 20, total: 115200 },
      { id: 'li5', productId: 'p4', productName: 'Advanced Approval Engine', description: 'Annual × 3', quantity: 3, unitPrice: 1200, discount: 0, total: 3600 },
    ],
    approvalSteps: [
      { id: 'as4', approverName: 'Director of Sales', approverEmail: 'sales-dir@company.com', approverRole: 'Sales Director', status: 'pending', comment: '', decidedAt: null, order: 1 },
      { id: 'as5', approverName: 'VP Revenue', approverEmail: 'vp-rev@company.com', approverRole: 'VP Revenue', status: 'pending', comment: '', decidedAt: null, order: 2 },
    ],
    currentApprovalStep: 0,
    createdAt: '2024-04-25',
    sentAt: null,
    viewedAt: null,
  },
  {
    id: 'pr3',
    dealId: 'd3',
    companyId: 'c3',
    title: 'Renewal + Advanced Approvals — Meridian Finance',
    status: 'draft',
    executiveSummary: 'Seamless renewal of Meridian Finance\'s Professional Plan with an upgrade to the Advanced Approval Engine, ensuring full regulatory compliance and streamlined multi-stakeholder deal management.',
    content: '',
    validUntil: '2024-05-10',
    totalValue: 35700,
    currency: 'USD',
    lineItems: [
      { id: 'li6', productId: 'p2', productName: 'Professional Plan', description: '10 seats × 12 months', quantity: 10, unitPrice: 149, discount: 0, total: 17880 },
      { id: 'li7', productId: 'p4', productName: 'Advanced Approval Engine', description: 'Annual', quantity: 1, unitPrice: 1200, discount: 0, total: 1200 },
    ],
    approvalSteps: [
      { id: 'as6', approverName: 'Director of Sales', approverEmail: 'sales-dir@company.com', approverRole: 'Sales Director', status: 'pending', comment: '', decidedAt: null, order: 1 },
    ],
    currentApprovalStep: 0,
    createdAt: '2024-04-28',
    sentAt: null,
    viewedAt: null,
  },
];

export const MOCK_OUTREACH: OutreachMessage[] = [
  {
    id: 'o1',
    companyId: 'c5',
    dealId: 'd4',
    subject: 'Transforming Quantum Healthcare\'s Vendor Approval Process — 3 Min Read',
    body: `Hi Dr. Williams,\n\nI came across Quantum Healthcare's recent expansion into digital-first patient services and wanted to share how we've helped similar healthcare organizations cut vendor approval cycles from 3 weeks down to 4 days — while maintaining full compliance.\n\nWould a 20-minute discovery call this week make sense?`,
    tone: 'consultative',
    status: 'opened',
    createdAt: '2024-04-22',
    sentAt: '2024-04-22',
    openedAt: '2024-04-23',
    repliedAt: null,
  },
  {
    id: 'o2',
    companyId: 'c2',
    dealId: 'd2',
    subject: 'NovaTech Multi-Entity Proposal — Updated Terms Inside',
    body: `Hi Marcus,\n\nFollowing our call, I've restructured the proposal to cover all three NovaTech subsidiaries under a unified platform agreement with a 20% volume discount.\n\nKey highlights:\n• Single sign-on across all entities\n• Centralized approval dashboard\n• Dedicated integration support\n\nLet me know if you'd like to walk through it together.`,
    tone: 'formal',
    status: 'sent',
    createdAt: '2024-04-25',
    sentAt: '2024-04-25',
    openedAt: null,
    repliedAt: null,
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  { id: 'a1', type: 'proposal_viewed', title: 'Proposal viewed', description: 'Apex Logistics opened your proposal', companyName: 'Apex Logistics', timestamp: '2024-04-24T14:32:00Z', proposalId: 'pr1' },
  { id: 'a2', type: 'deal_closed', title: 'Deal closed won', description: 'Skyward Retail signed — $17,880', companyName: 'Skyward Retail', timestamp: '2024-04-26T10:15:00Z', dealId: 'd5' },
  { id: 'a3', type: 'approval_granted', title: 'Approval granted', description: 'VP Revenue approved Apex proposal', companyName: 'Apex Logistics', timestamp: '2024-04-22T09:00:00Z', proposalId: 'pr1' },
  { id: 'a4', type: 'outreach_replied', title: 'Outreach replied', description: 'Dr. Aisha Williams replied to your message', companyName: 'Quantum Healthcare', timestamp: '2024-04-23T16:45:00Z' },
  { id: 'a5', type: 'proposal_sent', title: 'Proposal sent', description: 'Enterprise proposal sent to Apex Logistics', companyName: 'Apex Logistics', timestamp: '2024-04-23T11:00:00Z', proposalId: 'pr1' },
  { id: 'a6', type: 'deal_created', title: 'New deal created', description: 'Strategic partnership with Quantum Healthcare', companyName: 'Quantum Healthcare', timestamp: '2024-04-20T08:30:00Z', dealId: 'd4' },
];

export const DASHBOARD_METRICS: DashboardMetrics = {
  totalDeals: 5,
  totalPipelineValue: 1389580,
  proposalsSent: 1,
  proposalsApproved: 0,
  avgDealCycle: 42,
  winRate: 68,
  pendingApprovals: 2,
  openOutreach: 3,
};
