export interface Book {
  id: string;
  title: string;
  author: string;
  isbn: string;
  genres: string[];
  description: string;
  priceAED: number;
  condition: 'Like New' | 'Very Good' | 'Good' | 'Acceptable';
  rating: number;
  reviewCount: number;
  year: number;
  pages: number;
  language: string;
  isFeatured?: boolean;
}

export function getCoverUrl(isbn: string): string {
  return `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
}

export const BOOKS: Book[] = [
  {
    id: '1',
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    isbn: '9780439708180',
    genres: ['fantasy', 'coming-of-age', 'adventure', 'magical-realism', 'magic'],
    description: 'The magical tale of a young orphan who discovers he is a wizard and begins his education at Hogwarts School of Witchcraft and Wizardry.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.9,
    reviewCount: 842,
    year: 1997,
    pages: 309,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '9780141439518',
    genres: ['classic-literature', 'romance', 'historical-romance', 'coming-of-age', 'wit'],
    description: 'A sparkling comedy of manners and a heartfelt romance, following Elizabeth Bennet as she navigates issues of marriage, morality, and misconceptions.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.7,
    reviewCount: 723,
    year: 1813,
    pages: 432,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780061935466',
    genres: ['classic-literature', 'coming-of-age', 'drama', 'historical-fiction', 'literary-fiction'],
    description: 'A timeless masterpiece exploring racial injustice and moral growth through the eyes of young Scout Finch in Depression-era Alabama.',
    priceAED: 25,
    condition: 'Very Good',
    rating: 4.8,
    reviewCount: 631,
    year: 1960,
    pages: 336,
    language: 'English',
  },
  {
    id: '4',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '9780062315007',
    genres: ['adventure', 'philosophy', 'self-discovery', 'spirituality', 'feel-good'],
    description: 'A fable about following your dreams. A young shepherd travels from Spain to Egypt in search of treasure and learns the language of the universe.',
    priceAED: 30,
    condition: 'Like New',
    rating: 4.6,
    reviewCount: 891,
    year: 1988,
    pages: 208,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '5',
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    genres: ['sci-fi', 'dystopian', 'dark-fiction', 'literary-fiction'],
    description: 'A dystopian masterpiece about a totalitarian society where Big Brother watches your every move and independent thought is a crime.',
    priceAED: 25,
    condition: 'Good',
    rating: 4.7,
    reviewCount: 567,
    year: 1949,
    pages: 328,
    language: 'English',
  },
  {
    id: '6',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '9780062316110',
    genres: ['non-fiction', 'history', 'science', 'philosophy'],
    description: 'A sweeping history of the human species from the Stone Age to the twenty-first century, examining how we came to rule the world.',
    priceAED: 40,
    condition: 'Like New',
    rating: 4.5,
    reviewCount: 442,
    year: 2011,
    pages: 464,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '7',
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9780441013593',
    genres: ['sci-fi', 'fantasy', 'adventure', 'mythology'],
    description: 'Set on the desert planet Arrakis, young Paul Atreides finds himself embroiled in a treacherous struggle for the most precious substance in the universe.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.6,
    reviewCount: 389,
    year: 1965,
    pages: 688,
    language: 'English',
  },
  {
    id: '8',
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    isbn: '9780307588371',
    genres: ['thriller', 'psychological', 'crime', 'suspense', 'mystery'],
    description: 'On the morning of his fifth wedding anniversary, Nick Dunne reports his wife Amy has gone missing. A dark and twisting psychological thriller.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.2,
    reviewCount: 521,
    year: 2012,
    pages: 432,
    language: 'English',
  },
  {
    id: '9',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    genres: ['classic-literature', 'literary-fiction', 'historical-fiction', 'drama'],
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set against the glittering Jazz Age.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.3,
    reviewCount: 448,
    year: 1925,
    pages: 180,
    language: 'English',
  },
  {
    id: '10',
    title: 'Educated',
    author: 'Tara Westover',
    isbn: '9780399590504',
    genres: ['memoir', 'biography', 'self-discovery', 'coming-of-age', 'non-fiction'],
    description: 'A remarkable memoir about a young woman who grows up in a survivalist family in Idaho and goes on to earn a PhD from Cambridge.',
    priceAED: 35,
    condition: 'Like New',
    rating: 4.7,
    reviewCount: 387,
    year: 2018,
    pages: 352,
    language: 'English',
  },
  {
    id: '11',
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    isbn: '9780307473462',
    genres: ['thriller', 'crime', 'mystery', 'suspense'],
    description: 'A journalist and a hacker join forces to investigate a 40-year-old disappearance in a wealthy Swedish family, uncovering dark secrets.',
    priceAED: 35,
    condition: 'Good',
    rating: 4.4,
    reviewCount: 332,
    year: 2005,
    pages: 672,
    language: 'English',
  },
  {
    id: '12',
    title: 'Life of Pi',
    author: 'Yann Martel',
    isbn: '9780156027328',
    genres: ['adventure', 'survival', 'literary-fiction', 'philosophical', 'coming-of-age'],
    description: 'A young man stranded in the Pacific Ocean on a lifeboat with a Bengal tiger. A philosophical adventure unlike any other.',
    priceAED: 25,
    condition: 'Very Good',
    rating: 4.5,
    reviewCount: 412,
    year: 2001,
    pages: 326,
    language: 'English',
  },
  {
    id: '13',
    title: 'Eleanor Oliphant is Completely Fine',
    author: 'Gail Honeyman',
    isbn: '9780735220690',
    genres: ['feel-good', 'contemporary-fiction', 'comedy', 'drama'],
    description: 'Eleanor Oliphant has learned how to survive — but not how to live. A funny, tender, and ultimately joyful story about what it means to be human.',
    priceAED: 30,
    condition: 'Like New',
    rating: 4.4,
    reviewCount: 298,
    year: 2017,
    pages: 328,
    language: 'English',
  },
  {
    id: '14',
    title: 'Atomic Habits',
    author: 'James Clear',
    isbn: '9780735211292',
    genres: ['self-help', 'non-fiction', 'psychology', 'self-discovery'],
    description: 'The definitive guide to building good habits and breaking bad ones. Tiny changes that produce remarkable results.',
    priceAED: 40,
    condition: 'Like New',
    rating: 4.6,
    reviewCount: 521,
    year: 2018,
    pages: 320,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '15',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    isbn: '9780756404741',
    genres: ['fantasy', 'adventure', 'magic', 'coming-of-age'],
    description: "The legendary Kvothe tells the story of his life — his time at a legendary school for magic and his rise as the world's most notorious wizard.",
    priceAED: 40,
    condition: 'Very Good',
    rating: 4.7,
    reviewCount: 276,
    year: 2007,
    pages: 662,
    language: 'English',
  },
  {
    id: '16',
    title: 'Rebecca',
    author: 'Daphne du Maurier',
    isbn: '9780380730407',
    genres: ['gothic', 'mystery', 'suspense', 'dark-fiction', 'romance'],
    description: '"Last night I dreamt I went to Manderley again." A gothic masterpiece of psychological suspense and dark romance.',
    priceAED: 25,
    condition: 'Good',
    rating: 4.5,
    reviewCount: 334,
    year: 1938,
    pages: 384,
    language: 'English',
  },
  {
    id: '17',
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    isbn: '9781476738024',
    genres: ['feel-good', 'comedy', 'drama', 'contemporary-fiction', 'cozy'],
    description: 'A curmudgeon hides a big heart. A charming and funny story about love, community, and unexpected friendship.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.5,
    reviewCount: 289,
    year: 2012,
    pages: 337,
    language: 'English',
  },
  {
    id: '18',
    title: 'The Thursday Murder Club',
    author: 'Richard Osman',
    isbn: '9781984880567',
    genres: ['cozy-mystery', 'comedy', 'mystery', 'humor'],
    description: 'Four unlikely friends in a retirement village meet weekly to investigate unsolved crimes — until a real murder lands on their doorstep.',
    priceAED: 35,
    condition: 'Like New',
    rating: 4.3,
    reviewCount: 218,
    year: 2020,
    pages: 368,
    language: 'English',
  },
  {
    id: '19',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    isbn: '9780735224292',
    genres: ['contemporary-fiction', 'nature', 'coming-of-age', 'romance', 'mystery'],
    description: 'A young woman alone in the marshes of North Carolina raises herself and becomes a naturalist — until a murder draws her into the outside world.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.6,
    reviewCount: 467,
    year: 2018,
    pages: 384,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '20',
    title: 'Me Before You',
    author: 'Jojo Moyes',
    isbn: '9780143124542',
    genres: ['romance', 'drama', 'contemporary-fiction', 'love-story'],
    description: 'Louisa Clark takes a job caring for Will Traynor — a man whose life was changed in an instant. A love story that will change you too.',
    priceAED: 30,
    condition: 'Good',
    rating: 4.3,
    reviewCount: 356,
    year: 2012,
    pages: 369,
    language: 'English',
  },
  {
    id: '21',
    title: 'Good Omens',
    author: 'Terry Pratchett & Neil Gaiman',
    isbn: '9780060853976',
    genres: ['humor', 'fantasy', 'comedy', 'satire', 'wit'],
    description: 'An angel and a demon become unlikely friends as the apocalypse approaches. One of the funniest books about Armageddon ever written.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.6,
    reviewCount: 312,
    year: 1990,
    pages: 413,
    language: 'English',
  },
  {
    id: '22',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    isbn: '9780374533557',
    genres: ['non-fiction', 'psychology', 'science', 'philosophy'],
    description: 'Nobel laureate Kahneman explores the two systems that drive the way we think — fast intuition and slow deliberate reasoning.',
    priceAED: 40,
    condition: 'Like New',
    rating: 4.4,
    reviewCount: 287,
    year: 2011,
    pages: 499,
    language: 'English',
  },
  {
    id: '23',
    title: 'The Shadow of the Wind',
    author: 'Carlos Ruiz Zafón',
    isbn: '9780143034902',
    genres: ['gothic', 'mystery', 'literary-fiction', 'historical-fiction', 'dark-fiction'],
    description: 'In post-Civil War Barcelona, a boy discovers a mysterious book — and becomes entangled in the dark secret that connects its author to his own fate.',
    priceAED: 35,
    condition: 'Good',
    rating: 4.6,
    reviewCount: 198,
    year: 2001,
    pages: 486,
    language: 'English',
  },
  {
    id: '24',
    title: 'Into the Wild',
    author: 'Jon Krakauer',
    isbn: '9780385486804',
    genres: ['adventure', 'travel', 'memoir', 'non-fiction', 'survival'],
    description: 'The true story of Christopher McCandless, who abandoned a privileged life to hitchhike to Alaska and live in the wilderness.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.2,
    reviewCount: 276,
    year: 1996,
    pages: 224,
    language: 'English',
  },
  {
    id: '25',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    isbn: '9780141441146',
    genres: ['classic-literature', 'romance', 'gothic', 'coming-of-age', 'historical-romance'],
    description: 'The passionate tale of Jane Eyre — an orphan who becomes a governess and falls in love with the brooding, secretive Mr. Rochester.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.5,
    reviewCount: 402,
    year: 1847,
    pages: 624,
    language: 'English',
  },
  {
    id: '26',
    title: 'The Notebook',
    author: 'Nicholas Sparks',
    isbn: '9780446605236',
    genres: ['romance', 'love-story', 'drama', 'contemporary-fiction'],
    description: "An old man reads to a woman with Alzheimer's — the poignant tale of two young lovers separated by circumstance and reunited by devotion.",
    priceAED: 20,
    condition: 'Good',
    rating: 4.1,
    reviewCount: 312,
    year: 1996,
    pages: 214,
    language: 'English',
  },
  {
    id: '27',
    title: 'Mexican Gothic',
    author: 'Silvia Moreno-Garcia',
    isbn: '9780525620785',
    genres: ['gothic', 'horror', 'historical-fiction', 'mystery', 'dark-fiction'],
    description: 'A glamorous socialite investigates a remote mansion in 1950s Mexico, where she uncovers the dark, sinister secrets of an English family.',
    priceAED: 30,
    condition: 'Like New',
    rating: 4.3,
    reviewCount: 187,
    year: 2020,
    pages: 320,
    language: 'English',
  },
  {
    id: '28',
    title: 'The Power of Habit',
    author: 'Charles Duhigg',
    isbn: '9781400069286',
    genres: ['self-help', 'non-fiction', 'psychology', 'science'],
    description: 'Why we do what we do in life and business. An examination of the science behind habit formation in our lives, companies, and societies.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.3,
    reviewCount: 243,
    year: 2012,
    pages: 371,
    language: 'English',
  },
  {
    id: '29',
    title: 'Beach Read',
    author: 'Emily Henry',
    isbn: '9781984806734',
    genres: ['romance', 'comedy', 'contemporary-romance', 'feel-good'],
    description: 'A romance writer and a literary fiction writer swap genres for the summer — and maybe fall in love. Fresh, funny, and utterly charming.',
    priceAED: 30,
    condition: 'Like New',
    rating: 4.4,
    reviewCount: 221,
    year: 2020,
    pages: 361,
    language: 'English',
  },
  {
    id: '30',
    title: 'Outlander',
    author: 'Diana Gabaldon',
    isbn: '9780440212560',
    genres: ['historical-romance', 'adventure', 'romance', 'historical-fiction'],
    description: 'A WWII nurse is transported back to 18th-century Scotland and falls in love with a Highland warrior. Epic historical romance adventure.',
    priceAED: 35,
    condition: 'Good',
    rating: 4.5,
    reviewCount: 298,
    year: 1991,
    pages: 850,
    language: 'English',
  },
  {
    id: '31',
    title: 'Big Little Lies',
    author: 'Liane Moriarty',
    isbn: '9780425274866',
    genres: ['thriller', 'suspense', 'drama', 'mystery', 'contemporary-fiction'],
    description: 'Three mothers bond over shared school drop-offs. But the dark secrets and lies hidden beneath the surface lead to a shocking night.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.3,
    reviewCount: 287,
    year: 2014,
    pages: 460,
    language: 'English',
  },
  {
    id: '32',
    title: 'Never Let Me Go',
    author: 'Kazuo Ishiguro',
    isbn: '9781400078776',
    genres: ['dark-fiction', 'sci-fi', 'literary-fiction', 'drama'],
    description: 'A haunting story of three friends who grew up at a special boarding school, and the extraordinary, heartbreaking secret of who they really are.',
    priceAED: 30,
    condition: 'Good',
    rating: 4.2,
    reviewCount: 198,
    year: 2005,
    pages: 288,
    language: 'English',
  },
  {
    id: '33',
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    isbn: '9780062073488',
    genres: ['mystery', 'crime', 'classic-literature', 'suspense', 'thriller'],
    description: 'Ten strangers are lured to a remote island. Then, one by one, they start to die. The world\'s best-selling mystery novel.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.6,
    reviewCount: 534,
    year: 1939,
    pages: 272,
    language: 'English',
  },
  {
    id: '34',
    title: 'Little Women',
    author: 'Louisa May Alcott',
    isbn: '9780316769174',
    genres: ['classic-literature', 'coming-of-age', 'family-saga', 'historical-fiction', 'romance'],
    description: 'The timeless story of the four March sisters — Meg, Jo, Beth, and Amy — growing up during the American Civil War.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.4,
    reviewCount: 389,
    year: 1868,
    pages: 449,
    language: 'English',
  },
  {
    id: '35',
    title: 'Around the World in 80 Days',
    author: 'Jules Verne',
    isbn: '9780140449105',
    genres: ['adventure', 'classic-literature', 'comedy', 'travel'],
    description: 'Phileas Fogg bets that he can circumnavigate the globe in just eighty days. A thrilling adventure classic that still delights.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.3,
    reviewCount: 287,
    year: 1872,
    pages: 256,
    language: 'English',
  },
  {
    id: '36',
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    isbn: '9780307474278',
    genres: ['thriller', 'mystery', 'action', 'suspense'],
    description: 'A murder in the Louvre leads to a trail of clues hidden in Leonardo da Vinci\'s artworks. A high-octane global conspiracy thriller.',
    priceAED: 25,
    condition: 'Good',
    rating: 4.0,
    reviewCount: 621,
    year: 2003,
    pages: 490,
    language: 'English',
  },
  {
    id: '37',
    title: 'Chocolat',
    author: 'Joanne Harris',
    isbn: '9780140296365',
    genres: ['feel-good', 'cozy', 'domestic-fiction', 'magical-realism', 'contemporary-fiction'],
    description: 'A mysterious woman arrives in a French village and opens a chocolate shop. As she works her magic, the village slowly transforms.',
    priceAED: 25,
    condition: 'Very Good',
    rating: 4.2,
    reviewCount: 187,
    year: 1999,
    pages: 320,
    language: 'English',
  },
  {
    id: '38',
    title: 'Wild',
    author: 'Cheryl Strayed',
    isbn: '9780307592736',
    genres: ['memoir', 'adventure', 'travel', 'self-discovery', 'non-fiction'],
    description: 'A solo 1,100-mile journey along the Pacific Crest Trail, undertaken to heal after a period of profound loss and self-destruction.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.2,
    reviewCount: 219,
    year: 2012,
    pages: 336,
    language: 'English',
  },
  {
    id: '39',
    title: 'Charlie and the Chocolate Factory',
    author: 'Roald Dahl',
    isbn: '9780142410318',
    genres: ['fantasy', 'comedy', 'coming-of-age', 'feel-good', 'humor'],
    description: 'Charlie Bucket finds a Golden Ticket granting access to the magical world of Willy Wonka\'s chocolate factory. Pure Roald Dahl magic.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.6,
    reviewCount: 412,
    year: 1964,
    pages: 176,
    language: 'English',
  },
  {
    id: '40',
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    isbn: '9780345391803',
    genres: ['sci-fi', 'humor', 'comedy', 'satire', 'adventure', 'wit'],
    description: 'Moments before Earth is demolished, Arthur Dent is whisked off into space. The answer to life, the universe and everything is 42.',
    priceAED: 30,
    condition: 'Very Good',
    rating: 4.7,
    reviewCount: 487,
    year: 1979,
    pages: 193,
    language: 'English',
  },
  {
    id: '41',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    isbn: '9780064401883',
    genres: ['classic-literature', 'nature', 'cozy', 'coming-of-age'],
    description: 'A sickly, spoiled girl comes to live at her uncle\'s estate and discovers a locked garden — and begins to flourish alongside it.',
    priceAED: 15,
    condition: 'Good',
    rating: 4.5,
    reviewCount: 312,
    year: 1911,
    pages: 331,
    language: 'English',
  },
  {
    id: '42',
    title: 'Dracula',
    author: 'Bram Stoker',
    isbn: '9780141439846',
    genres: ['gothic', 'horror', 'classic-literature', 'dark-fiction'],
    description: 'The original vampire novel. Jonathan Harker travels to Transylvania and realizes his host Count Dracula is far from human.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.4,
    reviewCount: 287,
    year: 1897,
    pages: 488,
    language: 'English',
  },
  {
    id: '43',
    title: 'Matilda',
    author: 'Roald Dahl',
    isbn: '9780142410370',
    genres: ['fantasy', 'comedy', 'feel-good', 'coming-of-age', 'humor'],
    description: 'A little girl with extraordinary intelligence and telekinetic powers escapes her dreadful parents and the terrifying Miss Trunchbull.',
    priceAED: 20,
    condition: 'Very Good',
    rating: 4.7,
    reviewCount: 398,
    year: 1988,
    pages: 240,
    language: 'English',
  },
  {
    id: '44',
    title: 'The Rosie Project',
    author: 'Graeme Simsion',
    isbn: '9781476729084',
    genres: ['comedy', 'romance', 'feel-good', 'contemporary-fiction', 'humor'],
    description: 'A socially challenged genetics professor creates a questionnaire to find the perfect wife. Unexpectedly hilarious and heartwarming.',
    priceAED: 30,
    condition: 'Like New',
    rating: 4.3,
    reviewCount: 198,
    year: 2013,
    pages: 295,
    language: 'English',
  },
  {
    id: '45',
    title: 'A Wizard of Earthsea',
    author: 'Ursula K. Le Guin',
    isbn: '9780547773742',
    genres: ['fantasy', 'coming-of-age', 'mythology', 'adventure', 'magic'],
    description: 'A boy with extraordinary magical talent attends a school for wizards and must confront a terrifying shadow creature of his own making.',
    priceAED: 25,
    condition: 'Good',
    rating: 4.5,
    reviewCount: 224,
    year: 1968,
    pages: 198,
    language: 'English',
  },
  {
    id: '46',
    title: 'Three Men in a Boat',
    author: 'Jerome K. Jerome',
    isbn: '9780140437324',
    genres: ['humor', 'comedy', 'travel', 'classic-literature', 'wit'],
    description: 'Three men and a dog embark on a boating holiday on the Thames. One of the funniest books ever written in the English language.',
    priceAED: 20,
    condition: 'Good',
    rating: 4.4,
    reviewCount: 198,
    year: 1889,
    pages: 214,
    language: 'English',
  },
  {
    id: '47',
    title: 'The House in the Cerulean Sea',
    author: 'TJ Klune',
    isbn: '9781250217318',
    genres: ['fantasy', 'feel-good', 'romance', 'cozy', 'magical-realism'],
    description: 'A cozy magical story about a caseworker for magical children who discovers love and a place to belong in the most extraordinary setting.',
    priceAED: 35,
    condition: 'Like New',
    rating: 4.6,
    reviewCount: 187,
    year: 2020,
    pages: 394,
    language: 'English',
  },
  {
    id: '48',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    isbn: '9781577311522',
    genres: ['spirituality', 'philosophy', 'mindfulness', 'self-discovery', 'self-help'],
    description: 'A guide to spiritual enlightenment that teaches the power of living fully in the present moment and freeing yourself from your mind.',
    priceAED: 30,
    condition: 'Good',
    rating: 4.3,
    reviewCount: 312,
    year: 1997,
    pages: 229,
    language: 'English',
  },
  {
    id: '49',
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    isbn: '9780316017930',
    genres: ['non-fiction', 'psychology', 'biography', 'science', 'self-help'],
    description: 'What makes high achievers different? Gladwell explores the hidden advantages and extraordinary opportunities that lead to exceptional success.',
    priceAED: 35,
    condition: 'Very Good',
    rating: 4.4,
    reviewCount: 356,
    year: 2008,
    pages: 309,
    language: 'English',
  },
  {
    id: '50',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    isbn: '9780525559474',
    genres: ['feel-good', 'fantasy', 'literary-fiction', 'philosophical', 'contemporary-fiction'],
    description: 'A library between life and death. Nora Seed gets a chance to undo her regrets and try out all the lives she could have lived.',
    priceAED: 35,
    condition: 'Like New',
    rating: 4.5,
    reviewCount: 287,
    year: 2020,
    pages: 304,
    language: 'English',
    isFeatured: true,
  },
];

export function getBooksByMoodGenres(genres: string[]): Book[] {
  const scored = BOOKS.map((book) => {
    const matches = book.genres.filter((g) => genres.includes(g)).length;
    const score = matches * 10 + book.rating * 2 + Math.log(book.reviewCount + 1);
    return { book, score };
  });
  return scored
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .map(({ book }) => book);
}

export function getFeaturedBooks(): Book[] {
  return BOOKS.filter((b) => b.isFeatured);
}

export function getTopRatedBooks(limit = 8): Book[] {
  return [...BOOKS].sort((a, b) => b.rating - a.rating).slice(0, limit);
}
