export interface Book {
  id: string;
  title: string;
  titleAr?: string;
  author: string;
  isbn: string;
  genres: string[];
  description: string;
  collection: string;
  availability: 'In-Library' | 'Digital' | 'Both';
  rating: number;
  reviewCount: number;
  year: number;
  pages: number;
  language: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isRare?: boolean;
}

export function getCoverUrl(isbn: string): string {
  return `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
}

export const LIBRARY_COLLECTIONS = [
  {
    id: 'general',
    name: 'General Library',
    nameAr: 'المكتبة العامة',
    description: 'A vast collection of general interest books covering all topics and genres for all readers.',
    icon: '📚',
    floor: 'Floors 1–3',
    color: 'from-blue-600 to-blue-800',
  },
  {
    id: 'young-adult',
    name: 'Young Adult Library',
    nameAr: 'مكتبة الشباب',
    description: 'Curated reads for teenagers and young adults exploring identity, adventure, and the world.',
    icon: '🌱',
    floor: 'Floor 2',
    color: 'from-green-600 to-green-800',
  },
  {
    id: 'children',
    name: "Children's Library",
    nameAr: 'مكتبة الأطفال',
    description: 'A magical world of picture books, stories and educational titles for young readers.',
    icon: '🧒',
    floor: 'Floor 1',
    color: 'from-orange-500 to-orange-700',
  },
  {
    id: 'information',
    name: 'Information Centre',
    nameAr: 'مركز المعلومات',
    description: 'Academic journals, reference works, dissertations and research databases.',
    icon: '🔬',
    floor: 'Floor 4',
    color: 'from-indigo-600 to-indigo-800',
  },
  {
    id: 'map-atlas',
    name: 'Map & Atlas Library',
    nameAr: 'مكتبة الخرائط والأطالس',
    description: 'Historical maps, geographic atlases, and cartographic collections of rare value.',
    icon: '🗺️',
    floor: 'Floor 4',
    color: 'from-teal-600 to-teal-800',
  },
  {
    id: 'media-arts',
    name: 'Media & Arts Library',
    nameAr: 'مكتبة الإعلام والفنون',
    description: 'Film, music, photography, design and media studies across all creative disciplines.',
    icon: '🎨',
    floor: 'Floor 3',
    color: 'from-pink-600 to-rose-700',
  },
  {
    id: 'business',
    name: 'Business Library',
    nameAr: 'مكتبة الأعمال',
    description: 'Business, economics, finance, leadership and entrepreneurship resources.',
    icon: '💼',
    floor: 'Floor 5',
    color: 'from-slate-600 to-slate-800',
  },
  {
    id: 'emirates',
    name: 'Emirates Library',
    nameAr: 'مكتبة الإمارات',
    description: 'Arabic literature, Islamic studies, UAE heritage and Gulf cultural collections.',
    icon: '🌙',
    floor: 'Floor 5',
    color: 'from-amber-600 to-yellow-700',
  },
  {
    id: 'periodicals',
    name: 'Periodicals Library',
    nameAr: 'مكتبة الدوريات',
    description: 'Newspapers, magazines and journals spanning 325 years of publishing history.',
    icon: '📰',
    floor: 'Floor 6',
    color: 'from-gray-600 to-gray-800',
  },
  {
    id: 'special',
    name: 'Special Collections',
    nameAr: 'المجموعات الخاصة',
    description: 'Rare manuscripts, first editions, and treasures dating back to the 13th century.',
    icon: '🏛️',
    floor: 'Floor 7',
    color: 'from-yellow-600 to-amber-700',
  },
];

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'Palace Walk',
    titleAr: 'بين القصرين',
    author: 'Naguib Mahfouz',
    isbn: '9780385264662',
    genres: ['arabic-literature', 'historical-fiction', 'literary-fiction', 'heritage'],
    description: 'The Nobel Prize-winning first volume of the Cairo Trilogy — a sweeping portrait of an Egyptian family navigating tradition and modernity in early 20th-century Cairo.',
    collection: 'Emirates Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 312,
    year: 1956,
    pages: 512,
    language: 'Arabic / English',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'The Prophet',
    titleAr: 'النبي',
    author: 'Khalil Gibran',
    isbn: '9780394404288',
    genres: ['spiritual', 'poetry', 'philosophy', 'arabic-literature', 'mindfulness'],
    description: 'Gibran\'s masterpiece — 26 poetic essays on love, freedom, pain, joy, and the human spirit. One of the bestselling books of all time.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.8,
    reviewCount: 489,
    year: 1923,
    pages: 127,
    language: 'Arabic / English',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '9780062316110',
    genres: ['science', 'history', 'academic', 'research'],
    description: 'A sweeping examination of how Homo sapiens came to dominate the planet — from Stone Age foragers to modern empires of finance and technology.',
    collection: 'Information Centre',
    availability: 'Both',
    rating: 4.5,
    reviewCount: 421,
    year: 2011,
    pages: 464,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Atomic Habits',
    author: 'James Clear',
    isbn: '9780735211292',
    genres: ['self-help', 'motivational', 'personal-development', 'psychology'],
    description: 'A practical framework for building good habits and breaking bad ones. Tiny changes lead to remarkable results.',
    collection: 'Business Library',
    availability: 'Both',
    rating: 4.6,
    reviewCount: 534,
    year: 2018,
    pages: 320,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    isbn: '9780374533557',
    genres: ['business', 'psychology', 'science', 'economics'],
    description: 'Nobel laureate Kahneman reveals the two systems that drive the way we think and make decisions — and how to use them wisely.',
    collection: 'Business Library',
    availability: 'Both',
    rating: 4.4,
    reviewCount: 287,
    year: 2011,
    pages: 499,
    language: 'English',
  },
  {
    id: '6',
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    isbn: '9781594480003',
    genres: ['contemporary-fiction', 'heritage', 'middle-east', 'literary-fiction', 'feel-good'],
    description: 'A powerful story of friendship, betrayal, and redemption set against the backdrop of Afghanistan\'s turbulent history.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.6,
    reviewCount: 398,
    year: 2003,
    pages: 371,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '7',
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    isbn: '9780060883287',
    genres: ['fiction', 'magical-realism', 'literary-fiction', 'adventure'],
    description: 'The Nobel Prize-winning masterpiece tracing the Buendía family across seven generations in the mythical town of Macondo.',
    collection: 'General Library',
    availability: 'In-Library',
    rating: 4.6,
    reviewCount: 356,
    year: 1967,
    pages: 417,
    language: 'English',
  },
  {
    id: '8',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    isbn: '9780553380163',
    genres: ['science', 'academic', 'research', 'technology'],
    description: 'Hawking\'s landmark exploration of the universe — from the Big Bang to black holes — explained for general readers.',
    collection: 'Information Centre',
    availability: 'Both',
    rating: 4.4,
    reviewCount: 312,
    year: 1988,
    pages: 212,
    language: 'English',
  },
  {
    id: '9',
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    isbn: '9780316017930',
    genres: ['business', 'sociology', 'motivational', 'personal-development'],
    description: 'What separates the high achievers from the rest? Gladwell uncovers the hidden advantages and cultural legacies that shape exceptional success.',
    collection: 'Business Library',
    availability: 'Both',
    rating: 4.4,
    reviewCount: 356,
    year: 2008,
    pages: 309,
    language: 'English',
  },
  {
    id: '10',
    title: 'The Little Prince',
    titleAr: 'الأمير الصغير',
    author: 'Antoine de Saint-Exupéry',
    isbn: '9780156012195',
    genres: ['children', 'philosophy', 'feel-good', 'poetry', 'spiritual'],
    description: 'A timeless philosophical tale of a little prince who travels from planet to planet, meeting unusual characters and learning about love and friendship.',
    collection: "Children's Library",
    availability: 'Both',
    rating: 4.8,
    reviewCount: 478,
    year: 1943,
    pages: 96,
    language: 'English / Arabic / French',
    isFeatured: true,
  },
  {
    id: '11',
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    isbn: '9780439708180',
    genres: ['fantasy', 'children', 'adventure', 'young-adult', 'coming-of-age'],
    description: 'The magical tale of a young orphan who discovers he is a wizard and begins his extraordinary education at Hogwarts School of Witchcraft and Wizardry.',
    collection: "Children's Library",
    availability: 'Both',
    rating: 4.9,
    reviewCount: 842,
    year: 1997,
    pages: 309,
    language: 'English',
    isFeatured: true,
  },
  {
    id: '12',
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9780441013593',
    genres: ['sci-fi', 'fantasy', 'adventure', 'research'],
    description: 'A landmark of science fiction set on the desert planet Arrakis — a story of politics, religion, ecology and human destiny.',
    collection: 'Young Adult Library',
    availability: 'In-Library',
    rating: 4.6,
    reviewCount: 389,
    year: 1965,
    pages: 688,
    language: 'English',
  },
  {
    id: '13',
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    genres: ['sci-fi', 'current-affairs', 'politics', 'literary-fiction'],
    description: 'A chilling vision of a totalitarian future where Big Brother watches every citizen. Essential reading on freedom, surveillance and truth.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 567,
    year: 1949,
    pages: 328,
    language: 'English',
  },
  {
    id: '14',
    title: 'Becoming',
    author: 'Michelle Obama',
    isbn: '9781524763138',
    genres: ['biography', 'memoir', 'motivational', 'personal-development', 'current-affairs'],
    description: 'The intimate memoir of former US First Lady Michelle Obama — a deeply personal story of identity, purpose, and perseverance.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 412,
    year: 2018,
    pages: 448,
    language: 'English',
    isNew: true,
  },
  {
    id: '15',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    isbn: '9780140449334',
    genres: ['philosophy', 'spiritual', 'mindfulness', 'heritage'],
    description: 'The private reflections of a Roman Emperor — timeless wisdom on resilience, virtue and the art of living well.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 334,
    year: 180,
    pages: 254,
    language: 'English',
  },
  {
    id: '16',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780061935466',
    genres: ['literary-fiction', 'coming-of-age', 'current-affairs', 'feel-good'],
    description: 'A Pulitzer Prize-winning story of racial injustice and moral growth in Depression-era Alabama, told through the eyes of young Scout Finch.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.8,
    reviewCount: 631,
    year: 1960,
    pages: 336,
    language: 'English',
  },
  {
    id: '17',
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    isbn: '9780385474542',
    genres: ['literary-fiction', 'heritage', 'world-affairs', 'arabic-literature'],
    description: 'The tragic story of Okonkwo and the collapse of the Igbo culture under colonial pressure. Africa\'s most celebrated novel.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.5,
    reviewCount: 267,
    year: 1958,
    pages: 215,
    language: 'English',
  },
  {
    id: '18',
    title: 'Educated',
    author: 'Tara Westover',
    isbn: '9780399590504',
    genres: ['memoir', 'biography', 'personal-development', 'coming-of-age'],
    description: 'A remarkable memoir about a woman who grows up without formal schooling and earns a PhD from Cambridge through sheer determination.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 387,
    year: 2018,
    pages: 352,
    language: 'English',
    isNew: true,
  },
  {
    id: '19',
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    isbn: '9780345391803',
    genres: ['sci-fi', 'humor', 'comedy', 'fantasy', 'feel-good'],
    description: 'A wildly comic science fiction adventure. When Earth is demolished, Arthur Dent is swept into a galaxy-spanning journey. The answer is 42.',
    collection: 'Young Adult Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 487,
    year: 1979,
    pages: 193,
    language: 'English',
  },
  {
    id: '20',
    title: 'Matilda',
    author: 'Roald Dahl',
    isbn: '9780142410370',
    genres: ['children', 'fantasy', 'feel-good', 'humor', 'coming-of-age'],
    description: 'A little girl with extraordinary powers escapes her dreadful family and the terrifying Miss Trunchbull. Pure Roald Dahl magic.',
    collection: "Children's Library",
    availability: 'Both',
    rating: 4.7,
    reviewCount: 398,
    year: 1988,
    pages: 240,
    language: 'English',
  },
  {
    id: '21',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    isbn: '9780756404741',
    genres: ['fantasy', 'adventure', 'young-adult', 'fiction'],
    description: 'The legendary Kvothe narrates his life — from a gifted child to the world\'s most feared wizard. An extraordinary fantasy epic.',
    collection: 'Young Adult Library',
    availability: 'In-Library',
    rating: 4.7,
    reviewCount: 276,
    year: 2007,
    pages: 662,
    language: 'English',
  },
  {
    id: '22',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    isbn: '9781451648539',
    genres: ['biography', 'business', 'technology', 'leadership', 'entrepreneurship'],
    description: 'The definitive biography of Apple\'s visionary co-founder — a penetrating portrait of creativity, obsession and innovation.',
    collection: 'Business Library',
    availability: 'Both',
    rating: 4.4,
    reviewCount: 312,
    year: 2011,
    pages: 656,
    language: 'English',
    isNew: true,
  },
  {
    id: '23',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '9780141439518',
    genres: ['literary-fiction', 'romance', 'feel-good', 'coming-of-age'],
    description: 'Austen\'s beloved comedy of manners — Elizabeth Bennet and the infuriating Mr. Darcy in one of the greatest love stories ever told.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.7,
    reviewCount: 723,
    year: 1813,
    pages: 432,
    language: 'English',
  },
  {
    id: '24',
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    isbn: '9780062073488',
    genres: ['fiction', 'feel-good', 'humor', 'coming-of-age'],
    description: 'Ten strangers are lured to a remote island and begin to die one by one. The world\'s best-selling mystery novel.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.6,
    reviewCount: 534,
    year: 1939,
    pages: 272,
    language: 'English',
  },
  {
    id: '25',
    title: 'The Alchemist',
    titleAr: 'الخيميائي',
    author: 'Paulo Coelho',
    isbn: '9780062315007',
    genres: ['spiritual', 'philosophy', 'motivational', 'adventure', 'feel-good'],
    description: 'A young shepherd\'s journey to find treasure teaches him the language of the universe and the importance of following one\'s Personal Legend.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.6,
    reviewCount: 891,
    year: 1988,
    pages: 208,
    language: 'English / Arabic',
    isFeatured: true,
  },
  {
    id: '26',
    title: 'Midnight\'s Children',
    author: 'Salman Rushdie',
    isbn: '9780812976533',
    genres: ['magical-realism', 'literary-fiction', 'heritage', 'history'],
    description: 'A Booker Prize winner — a child born at the moment of India\'s independence discovers he has telepathic powers. A dazzling magical epic.',
    collection: 'Special Collections',
    availability: 'In-Library',
    rating: 4.3,
    reviewCount: 198,
    year: 1981,
    pages: 647,
    language: 'English',
    isRare: true,
  },
  {
    id: '27',
    title: 'Good Omens',
    author: 'Terry Pratchett & Neil Gaiman',
    isbn: '9780060853976',
    genres: ['humor', 'fantasy', 'comedy', 'feel-good', 'sci-fi'],
    description: 'An angel and a demon team up to prevent the apocalypse. One of the wittiest, most joyful fantasy novels ever written.',
    collection: 'Young Adult Library',
    availability: 'Both',
    rating: 4.6,
    reviewCount: 312,
    year: 1990,
    pages: 413,
    language: 'English',
  },
  {
    id: '28',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    genres: ['literary-fiction', 'history', 'coming-of-age', 'feel-good'],
    description: 'The Jazz Age, glittering parties, and the elusive Green Light. Fitzgerald\'s masterpiece on the American Dream and its beautiful illusions.',
    collection: 'General Library',
    availability: 'Both',
    rating: 4.3,
    reviewCount: 448,
    year: 1925,
    pages: 180,
    language: 'English',
  },
  {
    id: '29',
    title: 'National Geographic Atlas of the World',
    author: 'National Geographic Society',
    isbn: '9781426220586',
    genres: ['geography', 'atlas', 'travel', 'world-affairs', 'reference'],
    description: 'The definitive cartographic reference — comprehensive maps of every region, country, and geographic feature on Earth.',
    collection: 'Map & Atlas Library',
    availability: 'In-Library',
    rating: 4.8,
    reviewCount: 89,
    year: 2019,
    pages: 448,
    language: 'English',
    isRare: true,
  },
  {
    id: '30',
    title: 'The Interpretation of Dreams',
    titleAr: 'تفسير الأحلام',
    author: 'Sigmund Freud',
    isbn: '9780465097081',
    genres: ['academic', 'research', 'dissertations', 'information-science', 'philosophy'],
    description: 'Freud\'s foundational work introducing psychoanalysis — a cornerstone text for any researcher studying the human mind.',
    collection: 'Special Collections',
    availability: 'In-Library',
    rating: 4.2,
    reviewCount: 156,
    year: 1899,
    pages: 630,
    language: 'English',
    isRare: true,
  },
];

export function getBooksByMoodGenres(genres: string[]): Book[] {
  const scored = BOOKS.map((book) => {
    const matches = book.genres.filter((g) => genres.includes(g)).length;
    const score = matches * 10 + book.rating * 2 + Math.log(book.reviewCount + 1);
    return { book, score };
  });
  return scored
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .map(({ book }) => book);
}

export function getFeaturedBooks(): Book[] {
  return BOOKS.filter((b) => b.isFeatured);
}

export function getNewArrivals(): Book[] {
  return BOOKS.filter((b) => b.isNew);
}

export function getTopRatedBooks(limit = 8): Book[] {
  return [...BOOKS].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getBooksByCollection(collection: string): Book[] {
  return BOOKS.filter((b) => b.collection === collection);
}
