export interface Mood {
  id: string;
  label: string;
  labelAr: string;
  emoji: string;
  description: string;
  genres: string[];
  gradient: string;
  borderColor: string;
  collection: string;
}

export const MOODS: Mood[] = [
  {
    id: 'inspired',
    label: 'Feeling Inspired',
    labelAr: 'أشعر بالإلهام',
    emoji: '🌟',
    description: 'Uplift your spirit and motivate your mind',
    genres: ['self-help', 'biography', 'motivational', 'philosophy', 'personal-development'],
    gradient: 'from-yellow-50 to-amber-50',
    borderColor: 'border-amber-300',
    collection: 'General Library',
  },
  {
    id: 'heritage',
    label: 'Cultural Heritage',
    labelAr: 'التراث الثقافي',
    emoji: '🏛️',
    description: 'Explore Arabic and Islamic culture',
    genres: ['arabic-literature', 'islamic-studies', 'heritage', 'middle-east', 'uae-history'],
    gradient: 'from-orange-50 to-amber-50',
    borderColor: 'border-orange-300',
    collection: 'Emirates Library',
  },
  {
    id: 'curious',
    label: 'Curious & Learning',
    labelAr: 'فضولي ومتعلم',
    emoji: '🔍',
    description: 'Satisfy your hunger for knowledge',
    genres: ['science', 'history', 'technology', 'academic', 'research'],
    gradient: 'from-blue-50 to-indigo-50',
    borderColor: 'border-blue-300',
    collection: 'Information Centre',
  },
  {
    id: 'business',
    label: 'Business Mindset',
    labelAr: 'العقلية التجارية',
    emoji: '💼',
    description: 'Ideas that elevate your career',
    genres: ['business', 'economics', 'leadership', 'entrepreneurship', 'finance'],
    gradient: 'from-slate-50 to-gray-100',
    borderColor: 'border-slate-300',
    collection: 'Business Library',
  },
  {
    id: 'young',
    label: 'Young Readers',
    labelAr: 'للقراء الصغار',
    emoji: '🧒',
    description: 'Stories for children and young adults',
    genres: ['children', 'young-adult', 'educational', 'picture-books', 'coming-of-age'],
    gradient: 'from-green-50 to-emerald-50',
    borderColor: 'border-green-300',
    collection: "Children's Library",
  },
  {
    id: 'creative',
    label: 'Creative Soul',
    labelAr: 'الروح الإبداعية',
    emoji: '🎨',
    description: 'Art, media and creative expression',
    genres: ['arts', 'design', 'music', 'film', 'photography', 'architecture'],
    gradient: 'from-pink-50 to-rose-50',
    borderColor: 'border-pink-300',
    collection: 'Media & Arts Library',
  },
  {
    id: 'explorer',
    label: 'World Explorer',
    labelAr: 'مستكشف العالم',
    emoji: '🗺️',
    description: 'Journey through maps, cultures and places',
    genres: ['travel', 'geography', 'atlas', 'world-affairs', 'anthropology'],
    gradient: 'from-teal-50 to-cyan-50',
    borderColor: 'border-teal-300',
    collection: 'Map & Atlas Library',
  },
  {
    id: 'research',
    label: 'Deep Research',
    labelAr: 'بحث عميق',
    emoji: '📚',
    description: 'For serious study and academic work',
    genres: ['dissertations', 'research', 'information-science', 'reference', 'academic'],
    gradient: 'from-purple-50 to-violet-50',
    borderColor: 'border-purple-300',
    collection: 'Special Collections',
  },
  {
    id: 'fantasy',
    label: 'Fantasy & Fiction',
    labelAr: 'الخيال والروايات',
    emoji: '✨',
    description: 'Escape into imaginative worlds',
    genres: ['fiction', 'fantasy', 'sci-fi', 'magical-realism', 'adventure'],
    gradient: 'from-violet-50 to-indigo-50',
    borderColor: 'border-violet-300',
    collection: 'Young Adult Library',
  },
  {
    id: 'peaceful',
    label: 'Peaceful Evening',
    labelAr: 'مساء هادئ',
    emoji: '🌙',
    description: 'Gentle, reflective reads to wind down',
    genres: ['poetry', 'short-stories', 'memoir', 'spiritual', 'mindfulness'],
    gradient: 'from-indigo-50 to-blue-50',
    borderColor: 'border-indigo-300',
    collection: 'General Library',
  },
  {
    id: 'feelgood',
    label: 'Feel-Good Reads',
    labelAr: 'قراءات بهيجة',
    emoji: '😊',
    description: 'Warm stories that lift the spirit',
    genres: ['feel-good', 'humor', 'contemporary-fiction', 'romance', 'comedy'],
    gradient: 'from-amber-50 to-yellow-50',
    borderColor: 'border-amber-200',
    collection: 'General Library',
  },
  {
    id: 'informed',
    label: 'Informed Citizen',
    labelAr: 'مواطن مطلع',
    emoji: '📰',
    description: 'Stay current with the world',
    genres: ['current-affairs', 'politics', 'journalism', 'society', 'economics'],
    gradient: 'from-gray-50 to-slate-50',
    borderColor: 'border-gray-300',
    collection: 'Periodicals Library',
  },
];
