import type { AlgorithmDefinition, MoodOption } from './types'

// ── 15 Algorithm Definitions ───────────────────────────────────────────────
// Each definition is the single source of truth for UI copy + engine behaviour.
// "description" = what the user gets. "howItWorks" = plain-English AI logic.

export const ALGORITHMS: AlgorithmDefinition[] = [

  // ── DISCOVER CATEGORY ────────────────────────────────────────────────────

  {
    id: 'surprise_me',
    emoji: '🎲',
    name: 'Surprise Me',
    tagline: 'Break your usual pattern.',
    description: 'You\'ll get picks that match your taste but push you in a direction you wouldn\'t normally choose yourself. Think of it as a trusted friend who knows what you like but refuses to play it safe.',
    howItWorks: 'The AI looks at everything you\'ve enjoyed, then deliberately picks things at the edge of your comfort zone — high quality, genuinely relevant, but not what you\'d reach for on autopilot.',
    category: 'discover',
    categoryLabel: 'Discovery',
    gradient: 'from-violet-600 via-purple-600 to-fuchsia-600',
    accentColor: '#7c3aed',
    vibes: ['adventurous', 'fresh', 'unpredictable'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 3,
  },

  {
    id: 'hidden_gems',
    emoji: '💎',
    name: 'Hidden Gems',
    tagline: 'Loved by few. Made for you.',
    description: 'These are brilliant things that flew under the radar — not viral, not pushed by an algorithm, just genuinely great and perfectly matched to your taste. Everything here has been filtered to exclude anything mainstream or overhyped.',
    howItWorks: 'The AI cross-references your taste profile against items with fewer than 20% of the typical view count, but with high ratings from users who share your exact preferences. Popularity is treated as a negative signal here.',
    category: 'discover',
    categoryLabel: 'Discovery',
    gradient: 'from-cyan-600 via-teal-600 to-emerald-600',
    accentColor: '#0d9488',
    vibes: ['curated', 'underground', 'surprising'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music', 'podcast'],
    explorationLevel: 2,
  },

  {
    id: 'world_content',
    emoji: '🌍',
    name: 'From Around The World',
    tagline: 'Great content you\'d never stumble across.',
    description: 'Your taste translated into something completely different — international films, non-English series, music from cultures you\'ve never explored. Matched to what you love, but from corners of the world you\'ve never looked.',
    howItWorks: 'The AI matches the emotional tone and narrative style of things you\'ve rated highly, then filters to content from countries or languages that aren\'t in your history. It finds the foreign equivalent of your favourite things.',
    category: 'discover',
    categoryLabel: 'Discovery',
    gradient: 'from-orange-500 via-amber-500 to-yellow-500',
    accentColor: '#f59e0b',
    vibes: ['global', 'cultural', 'eye-opening'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 3,
  },

  {
    id: 'the_wildcard',
    emoji: '⚡',
    name: 'The Wildcard',
    tagline: 'Completely outside everything you know.',
    description: 'This one is intentionally unpredictable. The AI picks something with zero overlap with your usual taste — different genre, different mood, different world. For when you genuinely want to be thrown somewhere new.',
    howItWorks: 'The AI calculates the maximum distance from your taste profile and picks the highest-quality items from that opposite end. It\'s the only mode that treats familiarity as a reason to exclude something.',
    category: 'discover',
    categoryLabel: 'Discovery',
    gradient: 'from-rose-600 via-pink-600 to-fuchsia-600',
    accentColor: '#e11d48',
    vibes: ['bold', 'risky', 'experimental'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    badgeText: 'Brave picks',
    explorationLevel: 3,
  },

  // ── POPULAR CATEGORY ─────────────────────────────────────────────────────

  {
    id: 'trending_now',
    emoji: '🔥',
    name: 'Trending Right Now',
    tagline: 'What people are actually watching this week.',
    description: 'Not a list of all-time popularity — this is a live snapshot of what\'s gaining momentum in the last 7 days. Filtered to only show content that matches your taste so you\'re not just seeing what\'s popular in general.',
    howItWorks: 'The AI tracks the velocity of views, ratings and saves over the past 7 days, then cross-filters against your taste profile. Items trending globally but irrelevant to you are removed.',
    category: 'popular',
    categoryLabel: 'What\'s On',
    gradient: 'from-red-600 via-orange-500 to-yellow-500',
    accentColor: '#ea580c',
    vibes: ['current', 'buzzing', 'cultural moment'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    badgeText: 'Updated daily',
    explorationLevel: 2,
  },

  {
    id: 'new_and_rising',
    emoji: '✨',
    name: 'New & Rising',
    tagline: 'Fresh out — and already making waves.',
    description: 'Released in the last 90 days and already showing real momentum from genuine viewers. Not paid promotion, not platform placement — just new things that are earning attention organically and match your taste.',
    howItWorks: 'The AI filters to content released within 90 days, then ranks by early engagement velocity while removing algorithmically-boosted or sponsored content. Only things your kind of audience is choosing.',
    category: 'popular',
    categoryLabel: 'What\'s On',
    gradient: 'from-lime-600 via-green-500 to-emerald-500',
    accentColor: '#16a34a',
    vibes: ['fresh', 'early mover', 'new discovery'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music', 'product'],
    badgeText: 'Last 90 days',
    explorationLevel: 2,
  },

  {
    id: 'crowd_favourite',
    emoji: '👥',
    name: 'Crowd Favourite',
    tagline: 'Verified by real people, not promoted by platforms.',
    description: 'Every result here has earned its spot through genuine human ratings and reviews — not platform algorithms, not marketing budgets, not paid placements. Pure word-of-mouth quality, filtered to your interests.',
    howItWorks: 'The AI uses a statistical rating method (Wilson lower bound) that weighs the number of genuine reviews against average score. Items with one perfect rating rank lower than items with thousands of strong ones.',
    category: 'popular',
    categoryLabel: 'What\'s On',
    gradient: 'from-blue-600 via-indigo-500 to-violet-500',
    accentColor: '#4f46e5',
    vibes: ['trusted', 'proven', 'word of mouth'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music', 'product'],
    explorationLevel: 1,
  },

  {
    id: 'all_time_greats',
    emoji: '🏆',
    name: 'All-Time Greats',
    tagline: 'Things that were great then. Still great now.',
    description: 'No viral spikes, no hype cycles — just content that has maintained exceptional ratings for years and still holds up. These are the things people come back to and still recommend long after everyone else has moved on.',
    howItWorks: 'The AI filters for content that has sustained above an 8/10 average rating for 3+ years with a high volume of reviews. Ratings are adjusted for time, so older classics with fewer modern reviews still surface correctly.',
    category: 'popular',
    categoryLabel: 'What\'s On',
    gradient: 'from-yellow-600 via-amber-500 to-orange-500',
    accentColor: '#d97706',
    vibes: ['timeless', 'essential', 'legendary'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 1,
  },

  // ── PERSONAL CATEGORY ────────────────────────────────────────────────────

  {
    id: 'my_taste',
    emoji: '🧠',
    name: 'My Taste',
    tagline: 'What people exactly like you love.',
    description: 'The AI has found your people — other users who\'ve watched, rated and skipped the same things you have. This surface shows you what they loved that you haven\'t seen yet. No guessing, pure pattern matching.',
    howItWorks: 'Your interaction history is compared against millions of others to find the people whose tastes align most closely with yours. Results come from what those people genuinely loved, not from content metadata or genre tags.',
    category: 'personal',
    categoryLabel: 'Personalised',
    gradient: 'from-violet-700 via-purple-600 to-indigo-600',
    accentColor: '#7c3aed',
    vibes: ['personalised', 'precise', 'uncanny'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    badgeText: 'Needs history',
    explorationLevel: 1,
  },

  {
    id: 'more_like_this',
    emoji: '🎯',
    name: 'More Like This',
    tagline: 'You pick one thing. We find its cousins.',
    description: 'Pick something you loved and this mode finds everything that shares the same DNA — same tone, themes, pacing, emotional texture. Not just the same genre, but the same feel.',
    howItWorks: 'The AI analyses your chosen item\'s genre, narrative themes, director style, language, and tone. It then finds items with the highest similarity across all of those dimensions simultaneously, not just one.',
    category: 'personal',
    categoryLabel: 'Personalised',
    gradient: 'from-sky-600 via-blue-500 to-indigo-500',
    accentColor: '#0284c7',
    vibes: ['similar feel', 'safe bet', 'familiar but new'],
    requiresSeed: true,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 1,
  },

  {
    id: 'deep_dive',
    emoji: '🤿',
    name: 'Deep Dive',
    tagline: 'Go all in. Explore one thing completely.',
    description: 'You\'ve dipped a toe into something — a genre, an artist, a director, a universe — but never gone deep. This mode picks the perfect entry point and then maps the full journey in order from there.',
    howItWorks: 'The AI finds genres, directors or artists you\'ve sampled lightly (1-2 items) but never explored fully, then surfaces the definitive starting point and a curated path through that territory.',
    category: 'personal',
    categoryLabel: 'Personalised',
    gradient: 'from-teal-600 via-cyan-600 to-sky-600',
    accentColor: '#0891b2',
    vibes: ['deep', 'obsessive', 'immersive'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 2,
  },

  {
    id: 'comfort_rewatch',
    emoji: '🛋️',
    name: 'Comfort Zone',
    tagline: 'Zero risk. Guaranteed to hit.',
    description: 'Sometimes you don\'t want to discover anything new — you want to know before you start that you\'ll love it. Every pick here is backed by your strongest past signals, chosen for maximum certainty not novelty.',
    howItWorks: 'The AI uses only your highest-confidence predictions — items where your taste history most strongly signals a match. Exploration is turned to zero. This is pure exploitation of known preferences.',
    category: 'personal',
    categoryLabel: 'Personalised',
    gradient: 'from-pink-600 via-rose-500 to-red-500',
    accentColor: '#e11d48',
    vibes: ['cosy', 'reliable', 'no-brainer'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 1,
  },

  // ── CONTEXT CATEGORY ─────────────────────────────────────────────────────

  {
    id: 'mood_match',
    emoji: '🌙',
    name: 'Match My Mood',
    tagline: 'Tell us how you feel. We\'ll find the match.',
    description: 'The same person wants completely different things on a Sunday morning versus a Friday night. Pick your mood and every result is filtered to match that emotional state — tone, pacing, energy level, all of it.',
    howItWorks: 'Each mood maps to a specific set of emotional tone tags, energy levels and genre characteristics. The AI overlays that mood filter on your taste profile and only returns items where both signals align.',
    category: 'context',
    categoryLabel: 'Right Now',
    gradient: 'from-indigo-600 via-violet-600 to-purple-700',
    accentColor: '#6d28d9',
    vibes: ['mood-based', 'in the moment', 'emotional fit'],
    requiresSeed: false,
    requiresMood: true,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music'],
    explorationLevel: 2,
  },

  {
    id: 'quick_wins',
    emoji: '⚡',
    name: 'Quick Wins',
    tagline: 'The AI is most confident about these. No debate needed.',
    description: 'When you\'re tired of choosing and just want something that will definitely be good — this cuts through everything and gives you the picks the algorithm is most certain about. High confidence, no uncertainty, just results.',
    howItWorks: 'The AI surfaces only the items with the smallest confidence interval in its predictions — meaning it has the most data and the least doubt about your likely reaction. Designed for decision fatigue moments.',
    category: 'context',
    categoryLabel: 'Right Now',
    gradient: 'from-amber-500 via-yellow-500 to-lime-500',
    accentColor: '#ca8a04',
    vibes: ['decisive', 'effortless', 'just pick one'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: false,
    bestFor: ['movie', 'tv', 'music', 'product'],
    badgeText: 'For decision fatigue',
    explorationLevel: 1,
  },

  {
    id: 'right_now',
    emoji: '⏱️',
    name: 'Right Now',
    tagline: 'Tell us how long you have. We\'ll fit perfectly.',
    description: 'Only shows content that fits inside your available time — a 25-minute TV episode, a 90-minute film, a 3-song playlist. You never start something you can\'t finish.',
    howItWorks: 'The AI filters the entire catalog to items within ±10 minutes of your time window, then ranks by your taste profile within that subset. Duration is treated as a hard constraint, not a soft preference.',
    category: 'context',
    categoryLabel: 'Right Now',
    gradient: 'from-slate-600 via-zinc-600 to-neutral-600',
    accentColor: '#52525b',
    vibes: ['time-aware', 'no overrun', 'fits your schedule'],
    requiresSeed: false,
    requiresMood: false,
    requiresDuration: true,
    bestFor: ['movie', 'tv', 'music', 'podcast'],
    explorationLevel: 2,
  },

]

// ── Lookup helpers ─────────────────────────────────────────────────────────

export const ALGORITHM_MAP = Object.fromEntries(ALGORITHMS.map(a => [a.id, a])) as Record<string, AlgorithmDefinition>

export const ALGORITHMS_BY_CATEGORY = ALGORITHMS.reduce((acc, alg) => {
  if (!acc[alg.category]) acc[alg.category] = []
  acc[alg.category].push(alg)
  return acc
}, {} as Record<string, AlgorithmDefinition[]>)

export const CATEGORY_META = {
  discover:  { label: 'Discovery',    emoji: '🔭', description: 'Push past your usual patterns' },
  popular:   { label: "What's On",    emoji: '📡', description: 'The pulse of right now' },
  personal:  { label: 'Personalised', emoji: '✦',  description: 'Built entirely around you' },
  context:   { label: 'Right Now',    emoji: '⚡',  description: 'Matched to this moment' },
}

// ── Mood options ───────────────────────────────────────────────────────────

export const MOODS: MoodOption[] = [
  { id: 'chill',     emoji: '😌', label: 'Chill',      genres: ['drama', 'documentary', 'indie'],   keywords: ['slow', 'relaxed', 'quiet', 'calm'] },
  { id: 'excited',   emoji: '🤩', label: 'Hyped',      genres: ['action', 'thriller', 'adventure'], keywords: ['fast', 'intense', 'energetic', 'explosive'] },
  { id: 'nostalgic', emoji: '🕰️', label: 'Nostalgic',  genres: ['classic', 'retro', 'family'],      keywords: ['nostalgic', 'retro', 'childhood', 'classic'] },
  { id: 'focused',   emoji: '🎯', label: 'Focused',    genres: ['documentary', 'biography'],        keywords: ['educational', 'informative', 'factual'] },
  { id: 'social',    emoji: '🥂', label: 'Social',     genres: ['comedy', 'romance', 'animation'],  keywords: ['fun', 'lighthearted', 'feel-good'] },
  { id: 'dark',      emoji: '🖤', label: 'Dark',       genres: ['horror', 'noir', 'crime'],         keywords: ['dark', 'gritty', 'tense', 'disturbing'] },
  { id: 'uplifted',  emoji: '🌟', label: 'Need a Lift',genres: ['comedy', 'animation', 'musical'],  keywords: ['uplifting', 'inspiring', 'feel-good', 'happy'] },
  { id: 'curious',   emoji: '🧐', label: 'Curious',    genres: ['sci-fi', 'documentary', 'mystery'],keywords: ['mind-bending', 'complex', 'thought-provoking'] },
]
